### ISSUE TITLE
Type of ami

### ISSUE THREAD

**Issue by djinnka** [garutilorenzo/k8s-aws-terraform-cluster#4]
In repository error ami = "	ami-0cffefff2d52e0a23" need delete spaces. If try to create cluster by ReadMe error "ValidationError: You must use a valid fully-formed launch template. Invalid id: "	ami-0cffefff2d52e0a23" (expecting "ami-...")"

**Comment by garutilorenzo** [comment]
Hello @djinnka  there is a typo on `vars.tf`

```
variable "ami" {
  type    = string
  default = "	ami-0cffefff2d52e0a23"
}
```
please remove the leading space on `vars.tf` or override it on your *main.tf* file.
Please also find the correct ami id for your region.
